from .colors import ColorMapper, ColorSequence
from .constants import FieldMode, Property, ScaleType, ArrowStyle
from .graphics import ArrowAtlas
from .validators import EnumValidator, ClipingPercentiles, _count_function_parameters, _fatal_error, PositiveNumber, NonNegativeNumber, PositiveInt, CoordinateSequence, StrictBool, Callable
from .regions import SpatialRegion

from . import core as cr
from . import math_engine as me

from typing import Sequence
import taichi as ti
import numpy as np
import warnings



class Renderable:
    def render(self, scene: cr.Scene):
        pass

    def update(self, scene: cr.Scene):
        pass

    def _init(self, scene: cr.Scene):
        pass

class VectorEntity(Renderable):
    def __init__(self, vec_function, color_mapper: ColorMapper, color_property: Property, color_clipping_percentiles: Sequence[float]):
        self._is_initialized = False
        self.vec_function = vec_function
        self.color_mapper = color_mapper
        self.color_property = color_property
        self.color_clipping_percentiles = color_clipping_percentiles

    def _init_engine(self, scene) -> None:
        if isinstance(self.vec_function, me.VectorMathEngine):
            if self.base_angle_vector is not None or self.custom_color_function is not None:
                self.math_engine = self.vec_function.clone(base_angle_vector=self.base_angle_vector, custom_function=self.custom_color_function)
            else:
                self.math_engine = self.vec_function
        elif callable(self.vec_function):
            self.math_engine = me.VectorMathEngine(scene, self.vec_function, self.base_angle_vector, self.custom_color_function)
        else:
            _fatal_error(f"vec_function must be either a VectorMathEngine instance or a callable function. Provided type: {type(self.vec_function)}", error_type="TypeError")

    def evaluate_vector_field(self, x: float, y: float) -> tuple:
        """Evaluates the primary vector field function at the specified spatial coordinates.

        This method acts as a safe execution wrapper for the user-defined vector
        function. It delegates the execution to the internal evaluation handler,
        which manages potential numpy broadcasting issues, scalar fallbacks, and
        automatic time-parameter injection.

        Args:
            x (float or numpy.ndarray): The x-coordinate(s) in the mathematical world space.
            y (float or numpy.ndarray): The y-coordinate(s) in the mathematical world space.

        Returns:
            tuple: A tuple (vector_x, vector_y) representing the evaluated vector field components.

        Notes:
            * **Broadcasting:** This method fully supports NumPy broadcasting. You can pass single
              float values for pinpoint evaluation, or large multidimensional arrays (like those
              generated by `numpy.meshgrid`) to evaluate the entire mathematical space simultaneously.

        Example:
            Evaluating the field at a single focal point:
            ```python
            import FluxRender as fr

            # [Initializing the scene and coordinate system]

            field = fr.VectorField(
                vec_function = lambda x, y: (y, -x),
                color_property = fr.Property.VELOCITY
            )
            scene.add(field)

            vector_component_x, vector_component_y = field.evaluate_vector_field(1.0, 0.0)

            print(f"Vector field at (1.0, 0.0): ({vector_component_x}, {vector_component_y})")
            # Result: (0.0, -1.0)
            ```

            Evaluating the field at multiple points simultaneously using numpy arrays:
            ```python
            import numpy as np

            # Define the exact spatial points we want to analyze
            target_coordinates_x = np.array([0.0, 1.0, 2.0])
            target_coordinates_y = np.array([0.0, 1.0, 2.0])

            x_vectors, y_vectors = vec_field.evaluate_vector_field(
                target_coordinates_x,
                target_coordinates_y
            )
            print(f"Vector field at points (0,0), (1,1) and (2,2): [{x_vectors[0]}, {y_vectors[0]}] | [{x_vectors[1]}, {y_vectors[1]}] | [{x_vectors[2]}, {y_vectors[2]}]")
            ```
        """

        return self.math_engine.evaluate_primary_vector_function(x, y)

    def evaluate_angle_vector(self, x: float, y: float) -> tuple:
        """Evaluates the base reference angle vector at the specified spatial coordinates.

        This method determines whether the reference angle vector is a static
        coordinate pair or a dynamically evaluated mathematical function. If it is
        a callable function, it safely executes it, automatically injecting the
        current time if the function signature requires it.

        Args:
            x (float or numpy.ndarray): The x-coordinate(s) in the mathematical world space.
            y (float or numpy.ndarray): The y-coordinate(s) in the mathematical world space.

        Returns:
            tuple: A tuple (component_x, component_y) representing the evaluated reference vector components.

        Notes:
            * **Broadcasting:** This method fully supports NumPy broadcasting. You can pass single
              float values for pinpoint evaluation, or large multidimensional arrays (like those
              generated by `numpy.meshgrid`) to evaluate the entire mathematical space simultaneously.

        Example:
            Evaluating a dynamically rotating reference angle at the origin:
            ```python
            import FluxRender as fr
            import numpy as np

            # [Initializing the scene and coordinate system]

            def rotating_reference(x, y, t):
                direction_x = np.cos(t)
                direction_y = np.sin(t)
                return direction_x, direction_y

            field = fr.VectorField(
                vec_function = lambda x, y: (y, -x),
                color_property = fr.Property.ANGLE,
                base_angle_vector = rotating_reference
            )
            scene.add(field)

            # The engine automatically handles the underlying time injection
            angle_vector_x, angle_vector_y = field.evaluate_angle_vector(0.0, 0.0)

            print(f"Reference angle vector at the origin: ({angle_vector_x}, {angle_vector_y})")
            ```
        """

        return self.math_engine.evaluate_angle_vector(x, y)

    def evaluate_vector_function(self, user_defined_function, *spatial_arguments) -> tuple:
        """Evaluates a user-provided mathematical function, automatically handling time injection and vectorization.

        This method serves as a robust adapter for custom user logic. It analyzes the signature of the
        provided function to dynamically inject the simulation time if required. Furthermore, it attempts
        to execute the function using native NumPy vectorization for maximum performance. If the function
        is strictly scalar (e.g., uses standard Python `math` modules instead of `numpy`), it automatically
        falls back to `numpy.vectorize` to ensure compatibility across large coordinate grids.

        Args:
            user_defined_function (Callable): The custom function or lambda to evaluate.
            *spatial_arguments: The base spatial arrays to pass into the function (typically world_x, world_y).

        Returns:
            tuple: A tuple (evaluated_vector_x, evaluated_vector_y) containing the computed field components
                as sanitized NumPy arrays.

        Notes:
            * **Time Injection:** If `user_defined_function` accepts exactly one parameter more than the
              number of provided `*spatial_arguments` (e.g., taking x, y, and t), the current scene time
              is automatically injected during execution.
            * **Vectorization Fallback:** You do not need to write strictly vectorized NumPy code. Regular
              Python scalar operations will be caught and vectorized automatically, though writing native
              NumPy code is highly recommended for optimal rendering performance.


        Examples:
            Evaluating a custom mathematical perturbation with automatic time injection:
            ```python
            import FluxRender as fr
            import numpy as np

            # [Initializing the scene and coordinate system]

            field = fr.VectorField(
                vec_function = lambda x, y: (y, -x),
            )
            scene.add(field)

            # Notice the third parameter 't'. The engine detects this and injects it.
            def custom_wind_perturbation(x, y, t):
                perturbation_x = np.sin(x + t)
                perturbation_y = np.cos(y + t)
                return perturbation_x, perturbation_y

            spatial_coordinates_x = np.array([0.0, 1.0, 2.0])
            spatial_coordinates_y = np.array([0.0, 1.0, 2.0])

            result_vectors_x, result_vectors_y = field.evaluate_vector_function(
                custom_wind_perturbation,
                spatial_coordinates_x,
                spatial_coordinates_y
            )
            ```
        """

        return self.math_engine._safe_evaluate_vector_function(user_defined_function, *spatial_arguments)

    def evaluate_scalar_function(self, user_defined_function, *spatial_arguments) -> np.ndarray:
        """Evaluates a user-provided mathematical scalar function, automatically handling time injection and vectorization.

        This method serves as a robust adapter for custom user logic that maps spatial coordinates (and potentially
        vector components) to a single scalar value. It analyzes the signature of the provided function to dynamically
        inject the simulation time if required. It attempts to execute the function using native NumPy vectorization
        for maximum performance, automatically falling back to `numpy.vectorize` if strictly scalar Python operations
        are detected.

        Args:
            user_defined_function (Callable): The custom scalar function or lambda to evaluate.
            *spatial_arguments: The base spatial and/or vector arrays to pass into the function
                (e.g., evaluated_vector_x, evaluated_vector_y, world_x, world_y).

        Returns:
            numpy.ndarray: A single NumPy array containing the computed scalar values, properly
                sanitized and ready for rendering or further mathematical processing.

        Notes:
            * **Time Injection:** If `user_defined_function` accepts exactly one parameter more than the
              number of provided `*spatial_arguments`, the current scene time is automatically injected
              during execution.
            * **Vectorization Fallback:** You do not need to write strictly vectorized NumPy code. Regular
              Python scalar operations will be caught and vectorized automatically, though writing native
              NumPy code is highly recommended for optimal rendering performance.
            * **Scalar Output:** Unlike its vector counterpart, this method strictly expects the user's
              function to return a single value (or a single array) per spatial coordinate, not a tuple.

        Example:
            Calculating and printing a custom physical metric (like kinetic energy) at specific points,
            while the field continues to render its default colors visually:
            ```python
            import FluxRender as fr
            import numpy as np

            # [Initializing the scene and coordinate system]

            field = fr.VectorField(
                vec_function = lambda x, y: (y, -x),
            )
            scene.add(field)

            # Custom function that internally queries the field for vector data and calculates a scalar property (e.g., kinetic energy = 0.5 * (vx^2 + vy^2))
            def calculate_kinetic_energy(x, y):
                vector_dx, vector_dy = field.evaluate_vector_field(x, y)
                kinetic_energy = 0.5 * (vector_dx**2 + vector_dy**2)
                return kinetic_energy

            # Define the exact spatial points we want to analyze
            target_coordinates_x = np.array([0.0, 1.0, 2.0])
            target_coordinates_y = np.array([0.0, 1.0, 2.0])

            # Evaluate the custom metric across all points simultaneously
            energy_results = field.evaluate_scalar_function(
                calculate_kinetic_energy,
                target_coordinates_x,
                target_coordinates_y
            )

            print(f"Kinetic energy at points (0,0), (1,1) and (2,2): {energy_results}")
            ```
        """

        return self.math_engine._safe_evaluate_scalar_function(user_defined_function, *spatial_arguments)



@ti.dataclass
class VectorFieldConfig:
    thickness: float
    arrow_size: float

@ti.data_oriented
class VectorField(VectorEntity):
    """A visual entity that renders a mathematical vector field using directional arrows.

    The VectorField acts as the static, geometric counterpart to the dynamic ParticleSystem.
    It queries the underlying mathematical engine across a spatial grid and visualizes
    the results as a structured collection of arrows, where each arrow represents the
    local magnitude and direction of the field at a specific point in space.

    This class excels at topological analysis. It features highly advanced rendering
    modes (such as FieldMode.ZOOM_DENSITY_ADAPTIVE) that dynamically recalculate grid
    spacing based on the camera's zoom level and local mathematical chaos. By coupling
    it with a ColorMapper, complex physical properties (like divergence, curl, or
    custom tensor evaluations) can be instantly translated into intuitive, color-coded
    visual maps.
    """

    spacing_x = PositiveNumber()
    spacing_y = PositiveNumber()
    length = PositiveNumber()
    thickness = PositiveNumber()
    antyaliasing = StrictBool()
    draw_arrows = StrictBool()
    normalized = StrictBool()
    max_vectors = PositiveInt()
    arrow_size = PositiveNumber()
    arrow_style = EnumValidator(ArrowStyle)
    mode = EnumValidator(FieldMode)
    color_property = EnumValidator(Property)
    color_clipping_percentiles = ClipingPercentiles()

    def __init__(
                # Universal parameters
                self, vec_function,
                color_mapper: ColorMapper = ColorMapper(),
                color_property: Property = Property.VELOCITY,
                color_clipping_percentiles: Sequence[float] = (5.0, 95.0),
                spacing_x=None, spacing_y=None,
                normalized: bool=True, length=None, thickness=2,
                mode: FieldMode = FieldMode.ZOOM_DENSITY_ADAPTIVE,
                arrow_size=15, arrow_style=ArrowStyle.HARPOON, draw_arrows: bool = True,
                antyaliasing: bool = True,
                max_vectors: int = 10000,

                # Parameters specific to density adaptive modes (WORLD_DENSITY_ADAPTIVE and ZOOM_DENSITY_ADAPTIVE)
                details_factor: int = 6,
                chaos_sensitivity: float = 3.0,
                max_length_reduction: float = 0.6,

                # Parameters specific to Property.ANGLE color_property
                base_angle_vector = None,

                # Parameters specific to custom color function mode (when color_property is Property.CUSTOM_FUNCTION)
                custom_color_function = None
                ):
        """
        Parameters:
            vec_function (Callable/VectorMathEngine): The math driving the flow. A function taking (x, y)
                and optionally (t) returning vector components (dx, dy), or a pre-built VectorMathEngine.

                **IMPORTANT REFERENCE NOTE**: If you pass an existing VectorMathEngine instance
                AND simultaneously provide overriding parameters (such as `base_angle_vector`
                or `custom_color_function`), this entity will silently create an independent
                **clone** of the engine under the hood. Consequently, any subsequent modifications
                made to your original engine instance will NOT be reflected in this visual entity.
            color_mapper (ColorMapper): An instance of a ColorMapper that maps vector properties to colors. If min_value and max_value are not provided, they will be automatically calculated. (Default: ColorMapper())
            color_property (Property): The vector property used for coloring (e.g., velocity, divergence, curl, angle, or a custom function). (Default: Property.VELOCITY)
            color_clipping_percentiles (tuple): The percentiles used to clip the color values. Defaults to (5.0, 95.0).
            spacing_x (float): Horizontal spacing between vectors. Units depend on the mode:

                * **SCREEN_FIXED**: spacing is in screen pixels (e.g., 40). Default is 40.
                * **WORLD_FIXED**: spacing is in mathematical world units (e.g., 0.5). Default is 0.4.
                * **ZOOM_ADAPTIVE**: spacing is in screen pixels but scales with zooming. Default is 18.
                * **WORLD_DENSITY_ADAPTIVE**: spacing is the base spacing in world units. Acts as maximum spacing. Default is 0.4.
                * **ZOOM_DENSITY_ADAPTIVE**: base spacing in world units that scales with zooming. Default is 0.4.
            spacing_y (float): The vertical spacing between vectors. Same units and defaults as spacing_x.
            normalized (bool): Whether to normalize vectors to unit length for visualization purposes. (Default: True)
            length (float): The base length of the vectors. Units depend on the mode:

                * **SCREEN_FIXED**: length is in screen pixels. Default is 30.
                * **WORLD_FIXED**: length is in world units. Default is 0.3.
                * **ZOOM_ADAPTIVE**: length is in screen pixels. Default is 30.
                * **WORLD_DENSITY_ADAPTIVE**: length is in screen pixels but scales with local density based on max_length_reduction. Default is 30.
                * **ZOOM_DENSITY_ADAPTIVE**: length is in screen pixels but scales with local density. Default is 30.
            thickness (float): The thickness of the drawn vectors in pixels. (Default: 2)
            mode (FieldMode): The mode of vector field rendering determining spacing and scaling (default: FieldMode.ZOOM_DENSITY_ADAPTIVE):

                * **SCREEN_FIXED**: Attached to the screen, length/position independent of view.
                * **WORLD_FIXED**: Attached to the math world, length/position depend on view.
                * **ZOOM_ADAPTIVE**: Grid spacing dynamically adjusts based on zoom level.
                * **WORLD_DENSITY_ADAPTIVE**: Placement is selectively filtered based on local chaos.
                * **ZOOM_DENSITY_ADAPTIVE**: Hybrid approach (zoom scaling + topological filtering) - default.
            arrow_size (float): The size of the arrowheads in pixels. (Default: 15)
            arrow_style (ArrowStyle): The visual style of the arrowheads (e.g., OPEN, TRIANGLE_TIGHT, HARPOON). (Default: HARPOON)
            draw_arrows (bool): Whether to draw arrowheads at the end of vectors.
            antyaliasing (bool): Whether to apply anti-aliasing for smoother visuals. (Default: True)
            max_vectors (int): Maximum number of vectors to render. (Default: 10000)
            details_factor (int): **[Density Adaptive]** How many times denser is the arrow spacing compared to the standard spacing at points with the greatest chaos. (Default: 6)
            chaos_sensitivity (float): **[Density Adaptive]** How fast the density increases with chaos (directional derivatives magnitude). (Default: 3.0)
            max_length_reduction (float): **[Density Adaptive]** The maximum length reduction for arrows in the most chaotic areas. (Default: 0.6)
            base_angle_vector (tuple, list, or Callable): **[Property.ANGLE]** The reference vector used to calculate angles. Defined as:

                * **Static 2D vector**: tuple or list (e.g., [1.0, 0.0]). (Default: [1.0, 0.0])
                * **Vector function**: Callable taking (x, y) and optionally (t), returning components (comp_x, comp_y).
            custom_color_function (Callable, optional): **[Property.CUSTOM]** A user-defined function for calculating colors.

                To maximize performance, the engine strictly avoids redundant math. Since the
                VectorField or ParticleSystem already evaluates the primary vector function to
                render arrows or move particles, it passes these exact, pre-calculated results
                directly into your color function.

                The function must accept 4 or 5 parameters:

                * `vec_dx` (float/ndarray): The evaluated X vector difference (the pre-calculated result at the anchor point).
                * `vec_dy` (float/ndarray): The evaluated Y vector difference.
                * `world_x` (float/ndarray): The X anchor point (sampling coordinate) in world space, determined by the entity's internal grid mode or particle position.
                * `world_y` (float/ndarray): The Y anchor point in world space.
                * `t` (float, optional): The current simulation time (if the engine is time-dependent).

                Should return a scalar or a NumPy array. Use vectorized NumPy operations for maximum efficiency.


        Example:
            Basic setup for a simple vector field defined by a mathematical function, with default
            coloring based on velocity magnitude and directly defined VectorMathEngine:

            ```python
            import FluxRender as fr
            import numpy as np

            # [Initializing the scene and coordinate system]

            def my_field(x, y):
                return np.sin(x), np.cos(y)

            engine = fr.VectorMathEngine(primary_vector_function = my_field)
            field = fr.VectorField(
                vec_function = engine,
                mode = fr.FieldMode.SCREEN_FIXED,
            )

            scene.add(field)
            ```

            The same, but animated vector field and without directly defined VectorMathEngine (the engine will be created internally):
            ```python
            import FluxRender as fr
            import numpy as np

            # [Initializing the scene and coordinate system]

            def my_field(x, y, t):
                return np.sin(x + t), np.cos(y + t)

            field = fr.VectorField(
                vec_function = my_field,
                mode = fr.FieldMode.SCREEN_FIXED,
            )

            scene.add(field)
            ```
        """

        super().__init__(vec_function, color_mapper, color_property, color_clipping_percentiles)

        # Dynamic configuration GPU
        self._thickness = thickness
        self._arrow_size = arrow_size

        # Dynamic Python configuration
        self.draw_arrows = draw_arrows
        self.normalized = normalized
        self.arrow_style = arrow_style
        self.mode = mode
        self.detail_factor = details_factor # in the case of WORLD_DENSITY_ADAPTIVE/ZOOM_DENSITY_ADAPTIVE mode, how many times denser is the arrow spacing compared to the standard spacing (spacing_x and spacing_y) at the points with the greatest chaos
        self.chaos_sensitivity = chaos_sensitivity # in the case of WORLD_DENSITY_ADAPTIVE/ZOOM_DENSITY_ADAPTIVE mode, how fast the density increases with chaos (directional derivatives magnitude)
        self.max_length_reduction = max_length_reduction # in the case of WORLD_DENSITY_ADAPTIVE/ZOOM_DENSITY_ADAPTIVE mode, the maximum length reduction for arrows in the most chaotic areas (0.0 means no length reduction, 1.0 means arrows are reduced to points)

        self.custom_color_function = custom_color_function

        self.base_angle_vector = base_angle_vector

        # region Default spacing based on mode [blue]
        if spacing_x is None:
            if self.mode == FieldMode.SCREEN_FIXED:
                self.spacing_x = 40
            elif self.mode == FieldMode.ZOOM_ADAPTIVE:
                self.spacing_x = 18
            else:
                self.spacing_x = 0.4
        else:
            self.spacing_x = spacing_x

        if spacing_y is None:
            if self.mode == FieldMode.SCREEN_FIXED:
                self.spacing_y = 40
            elif self.mode == FieldMode.ZOOM_ADAPTIVE:
                self.spacing_y = 18
            else:
                self.spacing_y = 0.4
        else:
            self.spacing_y = spacing_y

        if length is None:
            if self.mode == FieldMode.SCREEN_FIXED or self.mode == FieldMode.ZOOM_ADAPTIVE or self.mode == FieldMode.WORLD_DENSITY_ADAPTIVE or self.mode == FieldMode.ZOOM_DENSITY_ADAPTIVE:
                self.length = 30.0
            else:
                self.length = 0.3
        else:
            self.length = length
        # endregion

        # Static configuration
        self.antyaliasing = antyaliasing
        self.max_vectors = max_vectors

        self.coords = None
        self.scene = None
        self.math_engine = None
        self._last_cam_state = None
        self.num_vectors = 0

        self._vec_positions = ti.Vector.field(4, dtype=float, shape=max_vectors) # x_start, y_start, x_end, y_end
        self._vec_colors = ti.Vector.field(4, dtype=float, shape=max_vectors) # RGBA

        self._vec_positions_np = np.zeros((self.max_vectors, 4), dtype=np.float32)
        self._vec_colors_np = np.zeros((self.max_vectors, 4), dtype=np.float32)

        self.arrow_atlas = ArrowAtlas(style=arrow_style)

        self.settings = VectorFieldConfig.field(shape=())

        self._is_initialized = True
        self._update_settings()

    def _init(self, scene) -> None:
        self._init_engine(scene)

    def _update_settings(self) -> None:
        """
        Updates dynamic settings in the VectorFieldConfig class.
        This allows you to dynamically change vector field properties (e.g., using a button)
        """

        self.settings[None] = VectorFieldConfig(
            thickness=self._thickness,
            arrow_size=self._arrow_size
        )

    def _flag_for_update(self, property_name: str) -> None:
        """
        Flags the vector field for update when a property changes.

        This method is called by property validators whenever a relevant property is updated.
        It checks which property was changed and sets the appropriate flags to ensure that
        the vector field is re-evaluated and re-rendered with the new configuration.

        Args:
            property_name (str): The name of the property that was updated (e.g., 'spacing_x', 'length', 'arrow_size').
        """

        if property_name in ['thickness', 'arrow_size']:
            self._update_settings() # Update GPU settings immediately for properties that don't require recalculating vector positions/colors
        elif property_name in ['arrow_style']:
            self.arrow_atlas = ArrowAtlas(style=self.arrow_style) # Recreate arrow atlas if the style changes
        else:
            self._last_cam_state = (0, 0, 0, 0, 0, 0) # Force full update by resetting last camera state


    def update_configuration(self) -> None:
        """
            This function refreshes a vector field.

            Most often used when editing parameters not strictly related to the VectorField object (e.g., changing parameters in ColorMapper).

            Example:
                If you change colors in ColorMapper:
                ```python
                my_color_mapper = ColorMapper()

                # [Set up your vector field with my_color_mapper]

                # a function called when you click a button that changes the color range in ColorMapper and updates the configuration in VectorField
                def on_click():
                    my_color_mapper.max_hue = 180
                    my_color_mapper.min_hue = 240

                    my_vector_field.update_configuration()
                ```
        """

        self._update_settings()
        self._last_cam_state = (0, 0, 0, 0, 0, 0)

    def change_mode(self, new_mode) -> None:
        """
        Changes the rendering mode of a vector field and updates the related parameters accordingly, using default values.

        Args:
            new_mode (FieldMode): The new rendering mode to switch to.

        Example:
            ```python
            import FluxRender as fr

            # [Initializing the scene and coordinate system and vector field]

            # a function called when you click a button that changes the vector field mode
            def on_click():
                my_vector_field.change_mode(fr.FieldMode.WORLD_FIXED)
            ```
        """
        self.mode = new_mode
        self._last_cam_state = (0, 0, 0, 0, 0, 0)

        if new_mode == FieldMode.SCREEN_FIXED:
            spacing = 40
            self.length = 30
        elif new_mode == FieldMode.ZOOM_ADAPTIVE:
            spacing = 18
            self.length = 30
        elif new_mode == FieldMode.WORLD_DENSITY_ADAPTIVE or new_mode == FieldMode.ZOOM_DENSITY_ADAPTIVE:
            spacing = 0.4
            self.length = 30
        else:
            # WORLD_FIXED
            spacing = 0.4
            self.length = 0.3

        self.spacing_x = spacing
        self.spacing_y = spacing


    @ti.kernel
    def _draw_lines_gpu(self, target: ti.template(), num: int): # type: ignore
        cfg = self.settings[None]

        thickness = cfg.thickness
        screen_width, screen_height = target.shape

        margin = thickness * 0.5 + 2.0

        for i in range(num):
            vec = self._vec_positions[i]
            color = self._vec_colors[i]

            start_point = ti.Vector([vec[0], vec[1]])
            end_point = ti.Vector([vec[2], vec[3]])
            line_vec = end_point - start_point # vector from start to end of the line

            if line_vec.norm_sqr() > 1e-5: # Only draw if the vector has a direction (not zero-length)
                len_sq = line_vec.dot(line_vec) # squared length of the line segment

                inverse_len_sq = 0.0
                if len_sq > 0.0:
                    inverse_len_sq = 1.0 / len_sq # precompute inverse of length squared

                dx = ti.abs(line_vec.x)
                dy = ti.abs(line_vec.y)


                # A more horizontal line
                if dx >= dy:
                    # Find the smaller x-coordinate and its corresponding y-coordinate
                    start_x = start_point.x
                    end_x = end_point.x
                    start_y = start_point.y
                    slope = line_vec.y / line_vec.x

                    if end_point.x < start_point.x:
                        start_x = end_point.x
                        end_x = start_point.x
                        start_y = end_point.y

                    loop_start_x = int(ti.max(0, start_x - margin))
                    loop_end_x = int(ti.min(screen_width, end_x + margin))

                    for x in range(loop_start_x, loop_end_x):
                        # For the current x, calculate the ideal y-coordinate on the line (without margin)
                        ideal_y = start_y + slope * (x - start_x)

                        # Then loop through the y-coordinates within the margin around the ideal y
                        loop_start_y = int(ti.max(0, ideal_y - margin))
                        loop_end_y = int(ti.min(screen_height, ideal_y + margin))

                        for y in range(loop_start_y, loop_end_y):
                            pixel = ti.Vector([float(x), float(y)])

                            start_dist = pixel - start_point # vector from start of the arrow to the pixel

                            # Project the pixel onto the line defined by start and end points, and clamp to the segment
                            t = ti.math.clamp(start_dist.dot(line_vec) * inverse_len_sq, 0.0, 1.0)

                            closest_point = start_dist - t * line_vec
                            dist_sq = closest_point.dot(closest_point) # squared distance from the pixel to the line

                            if dist_sq < margin * margin:
                                dist = ti.sqrt(dist_sq)
                                if ti.static(self.antyaliasing): # ti.static removes 'if' on compilation
                                    alpha_factor = 1.0 - ti.math.smoothstep(thickness * 0.5 - 0.5,
                                                                            thickness * 0.5 + 0.5,
                                                                            dist)

                                    if alpha_factor > 0.0:
                                        if color.w > 0.99 and alpha_factor > 0.99: # If the color is fully opaque, we can skip blending and directly set the pixel (optimization)
                                            target[x, y] = color
                                        else:
                                            existing = target[x, y]
                                            out_a = color.w * alpha_factor + existing.w * (1.0 - color.w * alpha_factor)
                                            out_rgb = (color.xyz * color.w * alpha_factor + existing.xyz * existing.w * (1.0 - color.w * alpha_factor)) / ti.max(out_a, 1e-6)
                                            target[x, y] = ti.Vector([out_rgb.x, out_rgb.y, out_rgb.z, out_a])
                                else:
                                    if dist <= thickness * 0.5:
                                        if color.w > 0.99: # If the color is fully opaque, we can skip blending and directly set the pixel (optimization)
                                            target[x, y] = color
                                        else:
                                            existing = target[x, y]
                                            src_a = color.w
                                            out_a = src_a + existing.w * (1.0 - src_a)
                                            out_rgb = (color.xyz * src_a + existing.xyz * existing.w * (1.0 - src_a)) / ti.max(out_a, 1e-6)
                                            target[x, y] = ti.Vector([out_rgb.x, out_rgb.y, out_rgb.z, out_a])

                # A more vertical line
                else:
                    # Find the smaller y-coordinate and its corresponding x-coordinate
                    start_y = start_point.y
                    end_y = end_point.y
                    start_x = start_point.x
                    slope = line_vec.x / line_vec.y

                    if end_point.y < start_point.y:
                        start_y = end_point.y
                        end_y = start_point.y
                        start_x = end_point.x

                    loop_start_y = int(ti.max(0, start_y - margin))
                    loop_end_y = int(ti.min(screen_height, end_y + margin))

                    for y in range(loop_start_y, loop_end_y):
                        # For the current y, calculate the ideal x-coordinate on the line (without margin)
                        ideal_x = start_x + slope * (y - start_y)

                        # Then loop through the x-coordinates within the margin around the ideal x
                        loop_start_x = int(ti.max(0, ideal_x - margin))
                        loop_end_x = int(ti.min(screen_width, ideal_x + margin))

                        for x in range(loop_start_x, loop_end_x):
                            pixel = ti.Vector([float(x), float(y)])

                            start_dist = pixel - start_point # vector from start of the arrow to the pixel

                            # Project the pixel onto the line defined by start and end points, and clamp to the segment
                            t = ti.math.clamp(start_dist.dot(line_vec) * inverse_len_sq, 0.0, 1.0)

                            closest_point = start_dist - t * line_vec
                            dist_sq = closest_point.dot(closest_point) # squared distance from the pixel to the line

                            if dist_sq < margin * margin:
                                dist = ti.sqrt(dist_sq)
                                if ti.static(self.antyaliasing): # ti.static removes 'if' on compilation
                                    alpha_factor = 1.0 - ti.math.smoothstep(thickness * 0.5 - 0.5,
                                                                            thickness * 0.5 + 0.5,
                                                                            dist)

                                    if alpha_factor > 0.0:
                                        if color.w > 0.99 and alpha_factor > 0.99: # If the color is fully opaque, we can skip blending and directly set the pixel (optimization)
                                            target[x, y] = color
                                        else:
                                            existing = target[x, y]
                                            out_a = color.w * alpha_factor + existing.w * (1.0 - color.w * alpha_factor)
                                            out_rgb = (color.xyz * color.w * alpha_factor + existing.xyz * existing.w * (1.0 - color.w * alpha_factor)) / ti.max(out_a, 1e-6)
                                            target[x, y] = ti.Vector([out_rgb.x, out_rgb.y, out_rgb.z, out_a])
                                else:
                                    if dist <= thickness * 0.5:
                                        if color.w > 0.99: # If the color is fully opaque, we can skip blending and directly set the pixel (optimization)
                                            target[x, y] = color
                                        else:
                                            existing = target[x, y]
                                            src_a = color.w
                                            out_a = src_a + existing.w * (1.0 - src_a)
                                            out_rgb = (color.xyz * src_a + existing.xyz * existing.w * (1.0 - src_a)) / ti.max(out_a, 1e-6)
                                            target[x, y] = ti.Vector([out_rgb.x, out_rgb.y, out_rgb.z, out_a])

    @ti.kernel
    def _draw_arrowheads_gpu(self, target: ti.template(), num: int, arrow_atlas: ti.template()): # type: ignore
        cfg = self.settings[None]

        # Pre-calculate inverse size to replace division with multiplication inside the loop (faster)
        arrow_size = cfg.arrow_size
        inv_arrow_size = 1.0 / arrow_size

        for i in range(num):
            vec = self._vec_positions[i]
            color = self._vec_colors[i]

            start_point = ti.Vector([vec[0], vec[1]])
            end_point = ti.Vector([vec[2], vec[3]])
            line_vec = end_point - start_point # vector from start to end of the line

            if line_vec.norm_sqr() > 1e-5: # Only draw if the vector has a direction (not zero-length)
                center_pos = end_point # Center of the arrow sprite is the tip of the vector

                # normalized_line_vec = line_vec.normalized()

                basis_forward = line_vec.normalized() # points along the arrow's direction.
                basis_right = ti.Vector([basis_forward.y, -basis_forward.x]) # points perpendicular to the arrow.


                # Calculate the bounding box of the area we need to sample from the arrow atlas
                radius = arrow_size * 0.75
                x_start = int(ti.max(0, center_pos.x - radius))
                x_end = int(ti.min(target.shape[0], center_pos.x + radius + 1))
                y_start = int(ti.max(0, center_pos.y - radius))
                y_end = int(ti.min(target.shape[1], center_pos.y + radius + 1))

                for x, y in ti.ndrange((x_start, x_end), (y_start, y_end)):
                    pixel = ti.Vector([float(x), float(y)])
                    diff = pixel - center_pos

                    # Project the pixel distance onto the basis vectors.
                    # This is mathematically equivalent to a rotation matrix but computationally cheaper/clearer.
                    local_x = diff.dot(basis_right)
                    local_y = diff.dot(basis_forward)

                    # Convert to UV space (0.0 to 1.0), using pre-calculated inverse size.
                    uv_x = (local_x * inv_arrow_size) + 0.5
                    uv_y = (local_y * inv_arrow_size) + 0.5

                    # color_arr = ti.Vector([0.0, 0.0, 0.0, 0.0])

                    # Check if UV is within the texture bounds (with slight padding to avoid edge artifacts)
                    if uv_x > 0.01 and uv_x < 0.99 and uv_y > 0.01 and uv_y < 0.99:
                        tex_color = arrow_atlas.sample(ti.Vector([uv_x, uv_y])) # Sample the texture

                        # Calculate final alpha combining texture alpha and tint color alpha
                        final_alpha = tex_color.w * color.w

                        if final_alpha > 0.01:
                            if color.w > 0.99 and final_alpha > 0.99: # If the color is fully opaque, we can skip blending and directly set the pixel (optimization)
                                target[x, y] = ti.Vector([
                                    color.x * tex_color.x,
                                    color.y * tex_color.y,
                                    color.z * tex_color.z,
                                    1.0
                                ])
                            else:
                                existing = target[x, y]
                                out_a = final_alpha + existing.w * (1.0 - final_alpha)

                                # Premultiplied alpha blending formula
                                src_rgb = color.xyz * tex_color.xyz * final_alpha
                                dst_rgb = existing.xyz * existing.w * (1.0 - final_alpha)

                                out_rgb = (src_rgb + dst_rgb) / ti.max(out_a, 1e-6)
                                target[x, y] = ti.Vector([out_rgb.x, out_rgb.y, out_rgb.z, out_a])



    def _get_density_adaptive_grid_coords(self, dense_spacing_x, dense_spacing_y, dense_mesh_x, dense_mesh_y) -> tuple:
        with np.errstate(divide='ignore', over='ignore', invalid='ignore'):
            # Evaluate vector field
            vector_x, vector_y = self.math_engine.evaluate_primary_vector_function(dense_mesh_x, dense_mesh_y)

            # Normalize vectors to evaluate only direction changes (curl/divergence)
            vector_lengths = np.hypot(vector_x, vector_y)
            vector_lengths[vector_lengths == 0] = 1.0
            normalized_x = vector_x / vector_lengths
            normalized_y = vector_y / vector_lengths

            # Calculate gradients (rate of change of the vector direction)
            derivative_nx_y, derivative_nx_x = np.gradient(normalized_x)
            derivative_ny_y, derivative_ny_x = np.gradient(normalized_y)

            # Chaos is the magnitude of the combined directional derivatives
            chaos_magnitude = np.sqrt(derivative_nx_x**2 + derivative_nx_y**2 + derivative_ny_x**2 + derivative_ny_y**2)

            # Map chaos to a continuous density requirement [0.0, 1.0]
            # Sensitivity controls how fast it reaches maximum density
            density_probability = np.clip(chaos_magnitude * self.chaos_sensitivity, 0.0, 1.0)

            # Apply smoothstep for better visual transition
            density_probability = density_probability * density_probability * (3.0 - 2.0 * density_probability)

            # determine which points belong to the base grid (which we always keep) and which are the additional dense points that we will filter based on chaos density
            expected_base_x = np.round(dense_mesh_x / self.spacing_x) * self.spacing_x
            expected_base_y = np.round(dense_mesh_y / self.spacing_y) * self.spacing_y

            is_base_grid_x = np.abs(dense_mesh_x - expected_base_x) < 1e-4
            is_base_grid_y = np.abs(dense_mesh_y - expected_base_y) < 1e-4
            mask_base_grid = is_base_grid_x & is_base_grid_y

            # Standard 4x4 Bayer matrix used for smooth density scaling
            bayer_matrix = np.array([
                [ 0,  8,  2, 10],
                [12,  4, 14,  6],
                [ 3, 11,  1,  9],
                [15,  7, 13,  5]
            ]) / 16.0

            # Calculate the mathematical integer coordinate in the infinite world grid
            global_index_x = np.round(dense_mesh_x / dense_spacing_x).astype(int)
            global_index_y = np.round(dense_mesh_y / dense_spacing_y).astype(int)

            # Extract the specific threshold for each point based on its world position
            bayer_thresholds = bayer_matrix[global_index_x % 4, global_index_y % 4]

            # A point spawns if its local chaos probability exceeds its Bayer threshold
            mask_adaptive_density = density_probability > bayer_thresholds

            # Combine: Always keep the base grid, add adaptive arrows where required
            final_keep_mask = mask_base_grid | mask_adaptive_density

            # Extract the chaos density for the surviving points
            surviving_densities = density_probability[final_keep_mask].flatten()

            # Calculate length multiplier.
            # If density is 0.0 (empty), multiplier is 1.0 (full length).
            # If density is 1.0 (packed), multiplier is 0.3 (30% length to avoid overlap).
            maximum_length_reduction = self.max_length_reduction
            length_scaling_multiplier = 1.0 - (surviving_densities * maximum_length_reduction)

            return dense_mesh_x[final_keep_mask].flatten(), dense_mesh_y[final_keep_mask].flatten(), length_scaling_multiplier

    def _calculate_adaptive_step(self, cam, target_density_x, target_density_y) -> tuple:
        row_step = cam.math_width / target_density_x
        col_step = cam.math_width / target_density_y

        magnitude_x = 10 ** np.floor(np.log10(row_step))
        magnitude_y = 10 ** np.floor(np.log10(col_step))
        residual_x = row_step / magnitude_x
        residual_y = col_step / magnitude_y

        if residual_x > 5:
            step_x = 5 * magnitude_x
        elif residual_x > 2:
            step_x = 2 * magnitude_x
        else:
            step_x = magnitude_x

        if residual_y > 5:
            step_y = 5 * magnitude_y
        elif residual_y > 2:
            step_y = 2 * magnitude_y
        else:
            step_y = magnitude_y

        return step_x, step_y

    def _get_grid_coords(self, cam, mode: FieldMode) -> tuple:

        spacing_x = self.spacing_x
        spacing_y = self.spacing_y
        coords = self.coords

        if mode == FieldMode.SCREEN_FIXED:
            x = np.arange(spacing_x//2, cam.width, spacing_x)
            y = np.arange(spacing_y//2, cam.height, spacing_y)

            xv, yv = np.meshgrid(x, y)

            # Convert screen coordinates to world coordinates
            x_world, y_world = coords.to_math(xv, yv)

            flattened_x = x_world.flatten()
            flattened_y = y_world.flatten()

            return flattened_x, flattened_y, np.ones_like(flattened_x)



        elif mode == FieldMode.WORLD_FIXED:
            start_x = np.floor(cam.x_min / spacing_x) * spacing_x
            start_y = np.floor(cam.y_min / spacing_y) * spacing_y

            x_range = np.arange(start_x, cam.x_max + spacing_x, spacing_x)
            y_range = np.arange(start_y, cam.y_max + spacing_y, spacing_y)

            xv, yv = np.meshgrid(x_range, y_range)

            flattened_x = xv.flatten()
            flattened_y = yv.flatten()

            return flattened_x, flattened_y, np.ones_like(flattened_x)



        elif mode == FieldMode.ZOOM_ADAPTIVE:
            target_density_x = 500 / self.spacing_x
            target_density_y = 500 / self.spacing_y

            step_x, step_y = self._calculate_adaptive_step(cam, target_density_x, target_density_y)

            start_x = np.floor(cam.x_min / step_x) * step_x
            x_range = np.arange(start_x, cam.x_max + step_x, step_x)

            start_y = np.floor(cam.y_min / step_y) * step_y
            y_range = np.arange(start_y, cam.y_max + step_y, step_y)

            xv, yv = np.meshgrid(x_range, y_range)

            flattened_x = xv.flatten()
            flattened_y = yv.flatten()

            return flattened_x, flattened_y, np.ones_like(flattened_x)



        elif mode == FieldMode.WORLD_DENSITY_ADAPTIVE:
            # How many times denser is the arrow spacing compared to the standard spacing (spacing_x and spacing_y) at the points with the greatest chaos
            detail_factor = self.detail_factor
            dense_spacing_x = self.spacing_x / detail_factor
            dense_spacing_y = self.spacing_y / detail_factor

            # Generate the dense grid (World Space)
            start_x = np.floor(cam.x_min / dense_spacing_x) * dense_spacing_x
            start_y = np.floor(cam.y_min / dense_spacing_y) * dense_spacing_y

            x_range = np.arange(start_x, cam.x_max + dense_spacing_x, dense_spacing_x)
            y_range = np.arange(start_y, cam.y_max + dense_spacing_y, dense_spacing_y)

            dense_mesh_x, dense_mesh_y = np.meshgrid(x_range, y_range)

            return self._get_density_adaptive_grid_coords(dense_spacing_x, dense_spacing_y, dense_mesh_x, dense_mesh_y)



        elif mode == FieldMode.ZOOM_DENSITY_ADAPTIVE:
            target_density_x = 5 / self.spacing_x
            target_density_y = 5 / self.spacing_y

            step_x, step_y = self._calculate_adaptive_step(cam, target_density_x, target_density_y)

            # How many times denser is the arrow spacing compared to the standard spacing (spacing_x and spacing_y) at the points with the greatest chaos
            detail_factor = self.detail_factor
            dense_spacing_x = step_x / detail_factor
            dense_spacing_y = step_y / detail_factor

            # Generate the dense grid (World Space)
            start_x = np.floor(cam.x_min / dense_spacing_x) * dense_spacing_x
            start_y = np.floor(cam.y_min / dense_spacing_y) * dense_spacing_y

            x_range = np.arange(start_x, cam.x_max + dense_spacing_x, dense_spacing_x)
            y_range = np.arange(start_y, cam.y_max + dense_spacing_y, dense_spacing_y)

            dense_mesh_x, dense_mesh_y = np.meshgrid(x_range, y_range)

            return self._get_density_adaptive_grid_coords(dense_spacing_x, dense_spacing_y, dense_mesh_x, dense_mesh_y)




        elif mode == FieldMode.RANDOM:
            pass



    def _fill_colors(self, values) -> None:
        c_min = self.color_mapper.min_value
        c_max = self.color_mapper.max_value

        # Determine color range if not set by the user
        if c_min is None or c_max is None:
            c_min, c_max = np.percentile(values, self.color_clipping_percentiles)

            if np.abs(c_max - c_min) < 1e-5: # If all values are almost the same, set range to [0.0, pi] if coloring by angle, or [0.0, 1.0] if coloring by velocity
                c_min = 0.0
                if property == Property.VELOCITY or property == Property.CONVECTIVE_ACCELERATION:
                    c_max = 1.0
                elif property == Property.ANGLE:
                    c_max = np.pi
                elif property == Property.DIVERGENCE or property == Property.CURL or property == Property.COMPONENT_X or property == Property.COMPONENT_Y or property == Property.JACOBIAN or property == Property.OKUBO_WEISS or property == Property.CUSTOM:
                    c_min = -1.0
                    c_max = 1.0

            values = np.clip(values, c_min, c_max)


        colors_rgba = self.color_mapper.map_array(values, min_value=c_min, max_value=c_max)
        self._vec_colors_np[:len(values)] = colors_rgba
        self._vec_colors.from_numpy(self._vec_colors_np)



    def render(self, scene: cr.Scene) -> None:
        cam = self.coords.gpu_cam[None]

        current_state = (cam.x_min, cam.x_max, cam.y_min, cam.y_max, cam.width, cam.height)
        if current_state == self._last_cam_state and\
           self.math_engine._is_vec_function_time_dependent == False and\
           (self.math_engine._is_angle_function_time_dependent == False or self.color_property != Property.ANGLE) and\
           (self.math_engine._is_custom_function_time_dependent == False or self.color_property != Property.CUSTOM):

            self._draw_lines_gpu(scene.scene_layer, self.num_vectors)
            if self.draw_arrows: self._draw_arrowheads_gpu(scene.scene_layer, self.num_vectors, self.arrow_atlas)
            return

        self._last_cam_state = current_state

        world_x, world_y, vector_length_multiplier = self._get_grid_coords(cam, self.mode)

        count = len(world_x)

        if count > self.max_vectors:
            count = self.max_vectors
            world_x = world_x[:count]
            world_y = world_y[:count]
            vector_length_multiplier = vector_length_multiplier[:count]

        vec_dx, vec_dy, color_values = self.math_engine.evaluate_field_and_property(self.color_property, world_x, world_y)
        self._fill_colors(color_values)

        scale_x = cam.pixels_per_unit_x
        scale_y = cam.pixels_per_unit_y

        px_start_x, px_start_y = self.coords.to_screen(world_x, world_y)

        if self.mode == FieldMode.SCREEN_FIXED or self.mode == FieldMode.ZOOM_ADAPTIVE or self.mode == FieldMode.WORLD_DENSITY_ADAPTIVE or self.mode == FieldMode.ZOOM_DENSITY_ADAPTIVE:
            vec_dx *= scale_x
            vec_dy *= scale_y

            lengths = np.hypot(vec_dx, vec_dy)
            lengths[lengths == 0] = 1.0 # Avoid division by zero for zero-length vectors
            with np.errstate(divide='ignore', over='ignore', invalid='ignore'):
                if self.normalized:
                    dynamic_length = self.length * vector_length_multiplier

                    vec_dx = vec_dx / lengths * dynamic_length
                    vec_dy = vec_dy / lengths * dynamic_length
                px_end_x = px_start_x + vec_dx
                px_end_y = px_start_y + vec_dy
        else:
            lengths = np.hypot(vec_dx, vec_dy)
            lengths[lengths == 0] = 1.0 # Avoid division by zero for zero-length vectors

            if self.normalized:
                vec_dx = vec_dx / lengths * self.length
                vec_dy = vec_dy / lengths * self.length
            x_end = world_x + vec_dx
            y_end = world_y + vec_dy

            px_end_x, px_end_y = self.coords.to_screen(x_end, y_end)


        data = np.column_stack((px_start_x, px_start_y, px_end_x, px_end_y)).astype(np.float32)
        self.num_vectors = count
        self._vec_positions_np[:count] = data
        self._vec_positions.from_numpy(self._vec_positions_np)
        self._vec_colors.from_numpy(self._vec_colors_np)

        self._draw_lines_gpu(scene.scene_layer, self.num_vectors)
        if self.draw_arrows: self._draw_arrowheads_gpu(scene.scene_layer, self.num_vectors, self.arrow_atlas)


    def __repr__(self):
        return f"<VectorField(vec_function={getattr(self.vec_function, '__name__', self.vec_function.__class__.__name__)}, mode={self.mode.name}, num_vectors={self.num_vectors})>"


    # region Getters and Setters [setters]
    @property
    def vec_function(self):
        return self._vec_function
    @vec_function.setter
    def vec_function(self, value):
        self._vec_function = value
        if self._is_initialized:
            self.math_engine = self.math_engine.clone(primary_vector_function=self._vec_function)
            self._last_cam_state = (0, 0, 0, 0, 0, 0)

    @property
    def color_mapper(self):
        return self._color_mapper
    @color_mapper.setter
    def color_mapper(self, value):
        if not isinstance(value, ColorMapper):
            _fatal_error(f"color_mapper must be an instance of ColorMapper, got {type(value)}")
        self._color_mapper = value
        if self._is_initialized:
            self._last_cam_state = (0, 0, 0, 0, 0, 0)

    @property
    def detail_factor(self):
        return self._detail_factor
    @detail_factor.setter
    def detail_factor(self, value):
        self._detail_factor = value
        if not self._is_initialized:
            return
        if self._mode == FieldMode.WORLD_DENSITY_ADAPTIVE or self._mode == FieldMode.ZOOM_DENSITY_ADAPTIVE:
            self._last_cam_state = (0, 0, 0, 0, 0, 0)
        else:
            warnings.warn(f"Setting detail_factor has no effect when mode is not WORLD_DENSITY_ADAPTIVE or ZOOM_DENSITY_ADAPTIVE. Current mode: {self._mode.name}", UserWarning, stacklevel=2)

    @property
    def chaos_sensitivity(self):
        return self._chaos_sensitivity
    @chaos_sensitivity.setter
    def chaos_sensitivity(self, value):
        self._chaos_sensitivity = value
        if self._is_initialized:
            if self._mode == FieldMode.WORLD_DENSITY_ADAPTIVE or self._mode == FieldMode.ZOOM_DENSITY_ADAPTIVE:
                self._last_cam_state = (0, 0, 0, 0, 0, 0)
            else:
                warnings.warn(f"Setting chaos_sensitivity has no effect when mode is not WORLD_DENSITY_ADAPTIVE or ZOOM_DENSITY_ADAPTIVE. Current mode: {self._mode.name}", UserWarning, stacklevel=2)

    @property
    def max_length_reduction(self):
        return self._max_length_reduction
    @max_length_reduction.setter
    def max_length_reduction(self, value):
        self._max_length_reduction = value
        if self._is_initialized:
            if self._mode == FieldMode.WORLD_DENSITY_ADAPTIVE or self._mode == FieldMode.ZOOM_DENSITY_ADAPTIVE:
                self._last_cam_state = (0, 0, 0, 0, 0, 0)
            else:
                warnings.warn(f"Setting max_length_reduction has no effect when mode is not WORLD_DENSITY_ADAPTIVE or ZOOM_DENSITY_ADAPTIVE. Current mode: {self._mode.name}", UserWarning, stacklevel=2)

    @property
    def base_angle_vector(self):
        return self._base_angle_vector
    @base_angle_vector.setter
    def base_angle_vector(self, value):
        self._base_angle_vector = value
        if self._is_initialized:
            if self._color_property == Property.ANGLE:
                self.math_engine = self.math_engine.clone(base_angle_vector=self._base_angle_vector)
                self._last_cam_state = (0, 0, 0, 0, 0, 0)
            else:
                warnings.warn(f"Setting base_angle_vector has no effect when color_property is not set to ANGLE. Current color_property: {self._color_property.name}", UserWarning, stacklevel=2)


    @property
    def custom_color_function(self):
        return self._custom_color_function
    @custom_color_function.setter
    def custom_color_function(self, value):
        self._custom_color_function = value
        if self._is_initialized:
            if self.color_property == Property.CUSTOM:
                self.math_engine = self.math_engine.clone(custom_function=self._custom_color_function)
                self._last_cam_state = (0, 0, 0, 0, 0, 0)
            else:
                warnings.warn(f"Setting custom_color_function has no effect when color_property is not set to CUSTOM. Current color_property: {self.color_property.name}", UserWarning, stacklevel=2)

    # endregion




@ti.data_oriented
class ParticleSystem(VectorEntity):
    """A dynamic visualizer that simulates thousands of particles flowing through a vector field.

    While a `VectorField` uses static arrows to show the direction of the math, a `ParticleSystem`
    brings it to life. It drops thousands of tiny "tracers" into your mathematical fluid and lets
    them flow. This is perfect for visualizing aerodynamics, fluid dynamics, or simply creating
    hypnotic, beautiful animations of your equations.
    """


    lifetime = PositiveNumber()
    speed = NonNegativeNumber()
    count = PositiveInt()
    normalize_speed = StrictBool()
    max_speed_percentile = PositiveNumber()
    radius = PositiveNumber()
    speed_scale = EnumValidator(ScaleType)
    color_property = EnumValidator(Property)
    color_clipping_percentiles = ClipingPercentiles()

    def __init__(
                self, vec_function,
                color_mapper: ColorMapper = ColorMapper(),
                count: int = 20000,
                lifetime: float = 3.0,
                radius: float = 1,
                color_property: Property = Property.VELOCITY,
                opacity_function = None, # function of time: [0, 1] -> [0, 1]
                speed: float = 1.0,
                normalize_speed = False,
                speed_scale: ScaleType = ScaleType.LINEAR,
                max_speed_percentile: float = 95.0, # from 0 to 100
                emitter = None,
                color_clipping_percentiles: Sequence[float] = (5.0, 95.0), # from 0 to 100, (min_percentile, max_percentile)

                # parameters for speed_scale.CUSTOM and normalize_speed = False
                scale_function = None, # function domain: [0, 1]

                # Parameters specific to Property.ANGLE color_property
                base_angle_vector = None,

                # Parameters specific to custom color function mode (when color_property is Property.CUSTOM_FUNCTION)
                custom_color_function = None
                ):
        """
        Args:
            vec_function (Callable/VectorMathEngine): The math driving the flow. A function taking (x, y)
                and optionally (t) returning vector components (dx, dy), or a pre-built VectorMathEngine.

                **IMPORTANT REFERENCE NOTE**: If you pass an existing VectorMathEngine instance
                AND simultaneously provide overriding parameters (such as `base_angle_vector`
                or `custom_color_function`), this entity will silently create an independent
                **clone** of the engine under the hood. Consequently, any subsequent modifications
                made to your original engine instance will NOT be reflected in this visual entity.
            color_mapper (ColorMapper): The palette used to paint the particles based on their physical properties. (Default: ColorMapper())
            count (int): How many particles to simulate at once. Higher numbers look denser but require
                more GPU power. (Default: 20000)
            lifetime (float): How many seconds a particle lives before it fades out and respawns
                at a new location. Keeps the screen from getting too chaotic. (Default: 3.0)
            radius (float): The visual size (thickness) of each particle dot in pixels. (Default: 1.0)
            color_property (Property): What mathematical aspect decides the particle's color
                (e.g., VELOCITY for speed, CURL for rotation, ANGLE for direction). (Default: Property.VELOCITY)
            opacity_function (Callable, optional): A custom fade-in/fade-out curve. A function that takes
                a particle's normalized age (0.0 = just born, 1.0 = about to die) and returns its opacity (0.0 to 1.0).
                If None, the default smoothing function will be applied.
            speed (float): The global "gas pedal" for the animation. Multiplies how fast particles
                move across the screen. (Default: 1.0)
            normalize_speed (bool): If True, ignores the mathematical length of the vectors—every particle
                moves at exactly the same speed (great for analyzing pure direction). If False, particles
                in strong currents move fast, and those in weak currents move slowly. (Default: False)
            speed_scale (ScaleType): How the raw math translates to visual speed on screen.
                Use LOGARITHMIC or EXPONENTIAL if your math produces extreme values. (Default: ScaleType.LINEAR)
            max_speed_percentile (float): Outlier protection (0 to 100). Clips the fastest physical vectors
                at this percentile. Prevents mathematical singularities (like dividing by zero) from shooting
                particles off the screen at infinite speed. (Default: 95.0)
            emitter (SpatialRegion or dict, optional): Controls where new particles are born:
                • Single region: Pass a `SpatialRegion` to force all particles to spawn inside that specific shape.
                • Weighted regions: Pass a dictionary mapping multiple `SpatialRegion` objects to numeric weights (e.g., `{main_vent: 3.0, side_vent: 1.0}`). The numbers act as relative probabilities (they don't need to sum to 1.0). In this example, a particle is 3 times more likely to spawn in the main vent than the side vent.
                If None, particles spawn randomly across the entire screen.
            color_clipping_percentiles (tuple): The (min, max) percentiles used to ignore extreme outliers
                when mapping colors, ensuring your color gradient isn't ruined by a single infinite value. (Default: (5.0, 95.0))

            scale_function (Callable, optional): **[Speed Scale CUSTOM]** A user-defined function mapping
                normalized vector lengths [0, 1] to output speeds [0, 1]. Used only when speed_scale is ScaleType.CUSTOM
                and normalize_speed is False.
            base_angle_vector (tuple, list, or Callable): **[Property.ANGLE]** The reference baseline for calculating angles.
                Can be a static [x, y] list or a dynamic vector function of (x, y, t).
            custom_color_function (Callable, optional): **[Property.CUSTOM]** A user-defined function for calculating colors.

                To maximize performance, the engine strictly avoids redundant math. Since the
                VectorField or ParticleSystem already evaluates the primary vector function to
                render arrows or move particles, it passes these exact, pre-calculated results
                directly into your color function.

                The function must accept 4 or 5 parameters:

                * `vec_dx` (float/ndarray): The evaluated X vector difference (the pre-calculated result at the anchor point).
                * `vec_dy` (float/ndarray): The evaluated Y vector difference.
                * `world_x` (float/ndarray): The X anchor point (sampling coordinate) in world space, determined by the entity's internal grid mode or particle position.
                * `world_y` (float/ndarray): The Y anchor point in world space.
                * `t` (float, optional): The current simulation time (if the engine is time-dependent).

                Should return a scalar or a NumPy array. Use vectorized NumPy operations for maximum efficiency.


        Example:
            Basic usage with a simple rotational field:
            ```python
            import FluxRender as fr

            # [Initializing the scene and coordinate system]

            def rotational_field(x, y):
                return -y, x

            particle_system = ParticleSystem(vec_function = rotational_field)

            scene.add(particle_system)
            ```

            The same example, but with particles colored by their angle and a custom color palette:
            ```python
            import FluxRender as fr

            def rotational_field(x, y):
                return -y, x

            # Blue Shade Color Mapping
            my_color_mapper = fr.ColorMapper(max_hue = 180, min_hue = 240, max_saturation = 1, min_saturation = 0.8, max_lightness = 0.6, min_lightness = 0.45)
            particle_system = fr.ParticleSystem(
                vec_function = rotational_field,
                color_mapper = my_color_mapper,
                color_property = fr.Property.ANGLE  # Color based on vector angle relative to base_angle_vector (default [1.0, 0.0])
            )

            scene.add(particle_system)
            ```
        """

        super().__init__(vec_function, color_mapper, color_property, color_clipping_percentiles)

        # Dynamic configuration GPU
        self.radius = radius

        # Dynamic Python configuration
        self.count = count
        self.lifetime = lifetime
        self.speed = speed
        self.normalize_speed = normalize_speed
        self.speed_scale = speed_scale
        self.scale_function = scale_function
        self.max_speed_percentile = max_speed_percentile
        self.opacity_function = opacity_function
        self.emitter = emitter

        self.custom_color_function = custom_color_function
        self.base_angle_vector = base_angle_vector


        self.coords = None
        self.scene = None
        self.math_engine = None


        self._particles_positions = ti.Vector.field(2, dtype=ti.float32, shape=count)
        self._particles_colors = ti.Vector.field(4, dtype=ti.float32, shape=count)

        self._particles_positions_np = np.zeros((count, 2), dtype=np.float32)
        self._particles_lifetimes_np = np.zeros(count, dtype=np.float32)
        self._particles_colors_np = np.zeros((count, 4), dtype=np.float32)

        self._is_initialized = True


    def _init(self, scene: cr.Scene):
        if self.emitter is None:
            self._particles_positions_np[:, 0] = np.random.uniform(-200, scene.width + 200, self.count)
            self._particles_positions_np[:, 1] = np.random.uniform(-100, scene.height + 100, self.count)
        self._particles_lifetimes_np[:] = np.random.uniform(0, self.lifetime, self.count)

        self._init_engine(scene)

    def _validate_opacity_function(self, opacity_function):
        if opacity_function is None:
            return self._default_opacity_function

        if not callable(opacity_function):
            _fatal_error(f"Opacity function must be callable (e.g., a function or lambda).", error_type="TypeError")

        count = _count_function_parameters(opacity_function)
        if count == 1:
            return opacity_function
        else:
            _fatal_error(
                f"Opacity function must accept 1 parameter (normalized_lifetime) or *args. "
                f"Provided function accepts {count}.",
                "ValueError"
            )

    def _validate_scale_function(self, scale_function):
        if scale_function is None:
            return None

        if not callable(scale_function):
            _fatal_error(f"Scale function must be callable (e.g., a function or lambda).", error_type="TypeError")

        count = _count_function_parameters(scale_function)
        if count == 1:
            return scale_function
        else:
            _fatal_error(
                f"Scale function must accept 1 parameter (normalized_speed) or *args. "
                f"Provided function accepts {count}.",
                "ValueError"
            )



    def _fill_colors(self, values):
        c_min = self.color_mapper.min_value
        c_max = self.color_mapper.max_value

        if c_min is None or c_max is None:
            c_min, c_max = np.percentile(values, self.color_clipping_percentiles)

            if np.abs(c_max - c_min) < 1e-5: # If all values are almost the same, set range to [0.0, pi] if coloring by angle, or [0.0, 1.0] if coloring by velocity
                c_min = 0.0
                if property == Property.VELOCITY or property == Property.CONVECTIVE_ACCELERATION:
                    c_max = 1.0
                elif property == Property.ANGLE:
                    c_max = np.pi
                elif property == Property.DIVERGENCE or property == Property.CURL or property == Property.COMPONENT_X or property == Property.COMPONENT_Y or property == Property.JACOBIAN or property == Property.OKUBO_WEISS or property == Property.CUSTOM:
                    c_min = -1.0
                    c_max = 1.0

            values = np.clip(values, c_min, c_max)


        try:
            opacity = self.opacity_function(self._particles_lifetimes_np / self.lifetime)
        except Exception:
            vectorized_opacity_function = np.vectorize(self.opacity_function)
            opacity = vectorized_opacity_function(self._particles_lifetimes_np / self.lifetime)

        colors_rgba = self.color_mapper.map_array(values, min_value=c_min, max_value=c_max)
        self._particles_colors_np[:len(values)] = colors_rgba
        self._particles_colors_np[:len(values), 3] *= opacity
        self._particles_colors.from_numpy(self._particles_colors_np)

    @ti.kernel
    def _render_gpu(self, target: ti.template(), radius: float): # type: ignore
        radius_squared = radius ** 2
        for i in range(self.count):
            pos = self._particles_positions[i]
            color = self._particles_colors[i]

            min_x = int(pos.x - radius)
            max_x = int(pos.x + radius + 1)
            min_y = int(pos.y - radius)
            max_y = int(pos.y + radius + 1)

            for x in range(min_x, max_x):
                for y in range(min_y, max_y):
                    if (x - pos.x) ** 2 + (y - pos.y) ** 2 <= radius_squared:
                        if 2 <= x < self.coords.width and 2 <= y < self.coords.height:
                            target[x, y] = color

    def _default_opacity_function(self, normalized_lifetime):
        """
        Default opacity function: Particles fade in and out smoothly over their lifetime, with maximum opacity at the midpoint of their life.
        """

        return -16 * (normalized_lifetime - 0.5)**4 + 1

    def _prepare_vector(self, dx, dy):
        """
        Normalizes and scales the vector field magnitudes for visualization.
        Applies linear, logarithmic, or exponential scaling to better display extreme values.
        """


        lengths = np.hypot(dx, dy)
        lengths[lengths == 0] = 1e-10 # Avoid division by zero for zero-length vectors
        maximum_display_value = (self.coords.math_width / 10.0) * self.speed

        if self.normalize_speed:
            dx = dx / lengths * maximum_display_value
            dy = dy / lengths * maximum_display_value
        else:
            # Use the 98th percentile to prevent single singularities (like 1/x approaching 0)
            # from crushing the scale of the entire vector field.

            statistical_maximum_length = max(np.percentile(lengths, self.max_speed_percentile), 1e-10)

            multiplier = 1.0
            normalized_lengths = np.clip(lengths / statistical_maximum_length, 0.0, 1.0)

            if self.speed_scale == ScaleType.LINEAR:
                multiplier = 1.0

            elif self.speed_scale == ScaleType.LOGARITHMIC:
                multiplier = np.log(1 + 9 * normalized_lengths) / np.log(10) + 0.5

            elif self.speed_scale == ScaleType.EXPONENTIAL:
                multiplier = (10 ** normalized_lengths - 1) / 9

            elif self.speed_scale == ScaleType.CUSTOM and self.scale_function is not None:
                try:
                    # The function can take list/array inputs and return list/array outputs (vectorized)
                    multiplier = self.scale_function(normalized_lengths)
                except Exception:
                    # The function is a regular Python function (for each point individually)
                    vectorized_function = np.vectorize(self.scale_function)
                    multiplier = vectorized_function(normalized_lengths)

            dx = dx / statistical_maximum_length * maximum_display_value * multiplier
            dy = dy / statistical_maximum_length * maximum_display_value * multiplier


        return dx, dy


    def render(self, scene: cr.Scene):

        mask_dead = self._particles_lifetimes_np <= 0

        if self.emitter is None:
            # Spawn new particles at random positions around the edges of the screen
            self._particles_positions_np[mask_dead, 0] = np.random.uniform(-200, scene.width + 200, np.sum(mask_dead))
            self._particles_positions_np[mask_dead, 1] = np.random.uniform(-100, scene.height + 100, np.sum(mask_dead))

            self._particles_lifetimes_np[mask_dead] = self.lifetime
        else:
            # Single emitter case
            if not isinstance(self.emitter, dict):

                dead_particle_indices = np.where(mask_dead)[0]
                total_dead_particles = len(dead_particle_indices)

                if self.emitter.active:
                    natural_emission_rate = self.count / self.lifetime
                    spawn_limit_per_frame = int(natural_emission_rate * scene.dt) + 1

                    if total_dead_particles > spawn_limit_per_frame:
                            dead_particle_indices = dead_particle_indices[:spawn_limit_per_frame]

                    particles_to_revive_this_frame = len(dead_particle_indices)

                    points_x, points_y = self.emitter.random_points_screen(particles_to_revive_this_frame)
                    self._particles_positions_np[dead_particle_indices, 0] = points_x
                    self._particles_positions_np[dead_particle_indices, 1] = points_y

                    self._particles_lifetimes_np[dead_particle_indices] = np.random.uniform(
                        self.lifetime / 2.0,
                        self.lifetime,
                        particles_to_revive_this_frame
                    )

            # Multiple emitters case (dictionary with emitter objects as keys and their corresponding emission probabilities as values)
            else:
                # Get the exact physical indices of the dead particles in the main array
                dead_particle_indices = np.where(mask_dead)[0]
                total_dead_particles = len(dead_particle_indices)

                if total_dead_particles > 0:
                    available_emitters = [em for em in list(self.emitter.keys()) if em.active == True]

                    if len(available_emitters) != 0:
                        natural_emission_rate = self.count / self.lifetime
                        spawn_limit_per_frame = int(natural_emission_rate * scene.dt) + 1

                        if total_dead_particles > spawn_limit_per_frame:
                            dead_particle_indices = dead_particle_indices[:spawn_limit_per_frame]

                        particles_to_revive_this_frame = len(dead_particle_indices)


                        emitter_probabilities = [self.emitter[em] for em in available_emitters]

                        # Ensure probabilities sum up exactly to 1.0
                        normalized_probabilities = np.array(emitter_probabilities, dtype=np.float32)
                        normalized_probabilities /= normalized_probabilities.sum()

                        # Calculate how many particles EACH emitter should spawn simultaneously
                        particles_per_emitter = np.random.multinomial(particles_to_revive_this_frame, normalized_probabilities)

                        current_index_offset = 0

                        for current_emitter, particle_count in zip(available_emitters, particles_per_emitter):
                            if particle_count > 0:
                                # Generate all required points for this specific emitter at once
                                points_x, points_y = current_emitter.random_points_screen(particle_count)

                                # Slice the exact chunk of dead indices for this emitter
                                target_indices_chunk = dead_particle_indices[current_index_offset : current_index_offset + particle_count]

                                # Assign the newly generated points directly to the main array
                                self._particles_positions_np[target_indices_chunk, 0] = points_x
                                self._particles_positions_np[target_indices_chunk, 1] = points_y

                                current_index_offset += particle_count

                        self._particles_lifetimes_np[dead_particle_indices] = np.random.uniform(
                            self.lifetime / 2.0,
                            self.lifetime,
                            particles_to_revive_this_frame
                        )


        new_mask_dead = self._particles_lifetimes_np <= 0
        self._particles_positions_np[new_mask_dead] = None, None

        pos_x, pos_y = self.coords.to_math(self._particles_positions_np[:, 0], self._particles_positions_np[:, 1])
        dx, dy, color_values = self.math_engine.evaluate_field_and_property(self.color_property, pos_x, pos_y)
        self._fill_colors(color_values)

        # Normalize speed
        dx, dy = self._prepare_vector(dx, dy)


        pos_x += dx * scene.dt
        pos_y += dy * scene.dt

        screen_pos_x, screen_pos_y = self.coords.to_screen(pos_x, pos_y)
        self._particles_positions_np[:, 0] = screen_pos_x
        self._particles_positions_np[:, 1] = screen_pos_y
        self._particles_positions.from_numpy(self._particles_positions_np)

        self._render_gpu(scene.trail_layer, self.radius)

        self._particles_lifetimes_np -= scene.dt

    def __repr__(self):
        return f"<ParticleSystem(count={self.count}, vec_function={getattr(self.vec_function, '__name__', self.vec_function.__class__.__name__)})>"

    # region Getters and Setters [setters]
    @property
    def vec_function(self):
        return self._vec_function
    @vec_function.setter
    def vec_function(self, value):
        self._vec_function = value
        if self._is_initialized:
            self.math_engine = self.math_engine.clone(primary_vector_function=self._vec_function)


    @property
    def color_mapper(self):
        return self._color_mapper
    @color_mapper.setter
    def color_mapper(self, value):
        if not isinstance(value, ColorMapper):
            _fatal_error(f"color_mapper must be an instance of ColorMapper, got {type(value)}")
        self._color_mapper = value
        if self._is_initialized:
            self._last_cam_state = (0, 0, 0, 0, 0, 0)


    @property
    def count(self):
        return self._count
    @count.setter
    def count(self, value):
        self._count = value
        if self._is_initialized:
            self._particles_positions = ti.Vector.field(2, dtype=ti.float32, shape=self._count)
            self._particles_colors = ti.Vector.field(4, dtype=ti.float32, shape=self._count)
            self._particles_positions_np = np.zeros((self._count, 2), dtype=np.float32)
            self._particles_lifetimes_np = np.zeros(self._count, dtype=np.float32)
            self._particles_colors_np = np.zeros((self._count, 4), dtype=np.float32)
            self._init(self.scene)


    @property
    def custom_color_function(self):
        return self._custom_color_function
    @custom_color_function.setter
    def custom_color_function(self, value):
        self._custom_color_function = value
        if self._is_initialized:
            if self.color_property == Property.CUSTOM:
                self.math_engine = self.math_engine.clone(custom_function=self._custom_color_function)
            else:
                warnings.warn(f"Setting custom_color_function has no effect when color_property is not set to CUSTOM. Current color_property: {self.color_property.name}", UserWarning, stacklevel=2)

    @property
    def emitter(self):
        return self._emitter
    @emitter.setter
    def emitter(self, value):
        if value is not None:
            if isinstance(value, dict):
                for key in value.keys():
                    if not isinstance(key, SpatialRegion):
                        _fatal_error(f"Emitter keys must be instances of SpatialRegion, got {type(key)}", error_type="TypeError")
                for val in value.values():
                    if not isinstance(val, (int, float)):
                        _fatal_error(f"Emitter probabilities (dict values) must be numeric (int or float), got {type(val)}", error_type="TypeError")
            elif not isinstance(value, SpatialRegion):
                _fatal_error(f"Emitter must be an instance of SpatialRegion or a dictionary of SpatialRegion keys and numeric values, got {type(value)}", error_type="TypeError")
        self._emitter = value


    @property
    def opacity_function(self):
        return self._opacity_function
    @opacity_function.setter
    def opacity_function(self, value):
        self._opacity_function = self._validate_opacity_function(value)

    @property
    def scale_function(self):
        return self._scale_function
    @scale_function.setter
    def scale_function(self, value):
        self._scale_function = self._validate_scale_function(value)
        if self._is_initialized:
            if self.speed_scale != ScaleType.CUSTOM or self.normalize_speed:
                warnings.warn(f"Setting scale_function has no effect when speed_scale is not set to CUSTOM or normalize_speed is True. Current speed_scale: {self.speed_scale.name}, normalize_speed: {self.normalize_speed}", UserWarning, stacklevel=2)


    @property
    def base_angle_vector(self):
        return self._base_angle_vector
    @base_angle_vector.setter
    def base_angle_vector(self, value):
        self._base_angle_vector = value
        if self._is_initialized:
            if self._color_property == Property.ANGLE:
                self.math_engine = self.math_engine.clone(base_angle_vector=self._base_angle_vector)
            else:
                warnings.warn(f"Setting base_angle_vector has no effect when color_property is not set to ANGLE. Current color_property: {self._color_property.name}", UserWarning, stacklevel=2)

    #endregion






